name: CI/CD (GHCR + Tailscale OAuth)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: teleetbot
      TAG: main
    steps:
      - uses: actions/checkout@v4

      # Make a lowercase owner and export it for later steps
      - name: Compute OWNER_LC
        run: 
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo $OWNER_LC

      - name: Log in to GHCR
        run: echo "${{ github.token }}" | docker login "$REGISTRY" -u "${{ github.actor }}" --password-stdin

      - name: Build
        run: docker build -t "$REGISTRY/$OWNER_LC/$IMAGE_NAME:$TAG" .

      - name: Push
        run: docker push "$REGISTRY/$OWNER_LC/$IMAGE_NAME:$TAG"


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Connect to tailnet via OAuth
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:github-cd
          use-cache: 'true'
        # Joins your tailnet as an ephemeral, tagged device (no 90d key). After this step,
        # the runner can reach homelab privately over Tailscale.

      - name: Sanity (TS reachability)
        run: |
          tailscale ping -c 3 fpynkhomelab || tailscale ping -c 3 ${{ secrets.HOMELAB_SSH_HOST }}
      # Explainer: verifies we can reach your Beelink via TS name or IP.

      - name: Deploy via Tailscale SSH (no keys)
        run: |
          tailscale ssh fpynk@fpynkhomelab -- '
            set -Eeuo pipefail
            cd /srv/apps/teleetbot            # go to compose project
            docker compose pull               # fetch new GHCR image
            docker compose up -d              # recreate container
            docker inspect -f "{{.State.Health.Status}}" te-leet-bot || true
            docker compose ps
          '
      # Explainer: executes the deploy commands over Tailscale SSH using tailnet identity + ACLs.